/*
* generated by Xtext
*/
package com.soluvas.glproto.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.soluvas.glproto.services.GlprotoGrammarAccess;

public class GlprotoParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GlprotoGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.soluvas.glproto.parser.antlr.internal.InternalGlprotoParser createParser(XtextTokenStream stream) {
		return new com.soluvas.glproto.parser.antlr.internal.InternalGlprotoParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public GlprotoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GlprotoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
