/*
* generated by Xtext
*/
package com.soluvas.glproto.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GlprotoAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/soluvas/glproto/parser/antlr/internal/InternalGlproto.tokens");
	}
}
