/*
* generated by Xtext
*/
package com.soluvas.glproto;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GlprotoUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.soluvas.glproto.ui.internal.GlprotoActivator.getInstance().getInjector("com.soluvas.glproto.Glproto");
	}
	
}
