/*
 * generated by Xtext
 */
package com.soluvas.glproto.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GlprotoUiModule extends com.soluvas.glproto.ui.AbstractGlprotoUiModule {
	public GlprotoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
