/*
 * generated by Xtext
 */
package com.soluvas.glproto;

import org.eclipse.xtext.generator.JavaIoFileSystemAccess;

import com.google.inject.Binder;
import com.soluvas.glproto.generator.ExtendedFileSystemAccess;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GlprotoRuntimeModule extends com.soluvas.glproto.AbstractGlprotoRuntimeModule {

	public Class<? extends JavaIoFileSystemAccess> bindIFileSystemAccess() {
		return ExtendedFileSystemAccess.class;
	}
	
	@Override
	public void configure(Binder binder) {
		super.configure(binder);
//		binder.bind(JavaIoFileSystemAccess.class).to(ExtendedFileSystemAccess.class);
	}
}
