/*
* generated by Xtext
*/
package com.soluvas.glproto.ui.contentassist;

import com.soluvas.glproto.ui.contentassist.AbstractGlprotoProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GlprotoProposalProvider extends AbstractGlprotoProposalProvider {

}
